// Banco de palavras do "Quem sou eu?" — organizado por categoria.
// Tudo em português (pt-BR). Mantenha cada lista com palavras jogáveis:
// concretas, conhecidas e fáceis de descrever por mímica/dicas.

const WORDS = {
  Animais: [
    "Cachorro",
    "Gato",
    "Elefante",
    "Girafa",
    "Leão",
    "Tigre",
    "Macaco",
    "Cavalo",
    "Vaca",
    "Galinha",
    "Pinguim",
    "Golfinho",
    "Tubarão",
    "Cobra",
    "Sapo",
    "Aranha",
    "Borboleta",
    "Coelho",
    "Urso",
    "Lobo",
    "Raposa",
    "Coruja",
    "Tartaruga",
    "Jacaré",
    "Canguru",
    "Panda",
    "Camelo",
    "Abelha",
    "Gavião",
    "Urubu",
    "Papagaio",
    "Pombo",
    "Rato",
    "Barata",
    "Mosquito",
    "Formiga",
    "Polvo",
    "Lula",
    "Caranguejo",
    "Baleia",
    "Capivara",
    "Zebra",
    "Hipopótamo",
  ],
  Famosos: [
    "Pelé",
    "Ayrton Senna",
    "Anitta",
    "Neymar",
    "Gisele Bündchen",
    "Ronaldinho Gaúcho",
    "Chico Buarque",
    "Caetano Veloso",
    "Whindersson Nunes",
    "Gusttavo Lima",
    "Marília Mendonça",
    "Luciano Huck",
    "Mc Kevin",
    "Mc Hariel",
    "Mc Ryan SP",
    "Mc Daniel",
    "Veigh",
    "Matuê",
    "L7nnon",
    "Filipe Ret",
    "Djonga",
    "Emicida",
    "Mano Brown",
    "Sabotage",
    "Racionais MCs",
    "Orochi",
    "Chefin",
    "KayBlack",
    "Mc Ig",
    "Mc PH",
    "Mc Livinho",
    "Mc Don Juan",
    "Luísa Sonza",
    "Pabllo Vittar",
    "Ludmilla",
    "Gloria Groove",
    "Jão",
    "Casimiro",
    "Chico Moedas",
    "Alanzoka",
    "Gaules",
    "Nobru",
    "Cerol",
    "Loud Coringa",
    "Virginia Fonseca",
    "Zé Felipe",
    "Bianca Andrade",
    "Jade Picon",
    "Mel Maia",
    "Bruna Marquezine",
    "Maisa",
    "Larissa Manoela",
    "Paolla Oliveira",
    "Vini Jr",
    "Rodrygo Goes",
    "Endrick",
    "Gabriel Barbosa",
    "Arrascaeta",
    "Alok",
    "Vintage Culture",
    "Pedro Sampaio",
    "Dennis DJ",
    "Mc Cabelinho",
    "Xamã",
    "Vulgo Bakongo",
    "Mc WM",
    "Felipe Neto",
    "Luccas Neto",
    "Vanessa Lopes",
    "Teto",
    "Recayd Moran",
    "Pocah",
    "Vitão",
  ],
  Objetos: [
    "Guarda-chuva",
    "Escova de dente",
    "Geladeira",
    "Controle remoto",
    "Travesseiro",
    "Tesoura",
    "Martelo",
    "Óculos",
    "Relógio",
    "Mochila",
    "Chave",
    "Vassoura",
    "Liquidificador",
    "Ventilador",
    "Carteira",
    "Celular",
    "Violão",
    "Espelho",
    "Lanterna",
    "Cadeira",
    "Balde",
    "Guarda-roupa",
    "Panela",
    "Abajur",
    "Caixa de som",
    "Tênis",
    "Boné",
    "Corrente",
    "Anel",
    "Carregador portátil",
    "Fone",
    "Skate",
    "Patinete",
    "Bola de futebol",
    "Videogame",
    "Controle",
    "Notebook",
    "Tablet",
    "Chaveiro",
    "Passaporte",
    "Cartão de crédito",
    "Moletom",
    "Mochila",
    "Pochete",
    "Chinelo",
    "Óculos de sol",
    "Perfume",
    "Desodorante",
    "Escova de cabelo",
    "Almofada",
    "Lençol",
    "Toalha",
    "Copo",
    "Prato",
    "Talher",
    "Poster",
    "Luz RGB",
    "Hoodie",
    "Adesivo com meme",
  ],
  Filmes: [
    "Titanic",
    "O Rei Leão",
    "Toy Story",
    "Vingadores",
    "Procurando Nemo",
    "Harry Potter",
    "Frozen",
    "Jurassic Park",
    "Homem-Aranha",
    "Batman",
    "Star Wars",
    "Shrek",
    "Matrix",
    "De Volta para o Futuro",
    "Cidade de Deus",
    "Tropa de Elite",
    "O Auto da Compadecida",
    "Velozes e Furiosos",
    "Pantera Negra",
    "Os Incríveis",
    "Carros",
    "Divertida Mente",
    "Coringa",
    "Interestelar",
    "A Origem",
    "Whiplash",
    "Clube da Luta",
    "Crepúsculo",
    "Jogos Vorazes",
    "Divergente",
    "Maze Runner",
    "Barbie",
    "Oppenheimer",
    "Avatar",
    "Minions",
    "Meu Malvado Favorito",
    "Kung Fu Panda",
    "Madagascar",
    "A Era do Gelo",
    "Moana",
    "Enrolados",
    "Viva A Vida é uma Festa",
    "Soul",
    "Ratatouille",
    "Monstros SAs",
    "Up Altas Aventuras",
    "Wall-E",
    "Tarzan",
    "Mulan",
    "Aladdin",
    "A Bela e a Fera",
    "Cinderela",
    "Branca de Neve",
    "Peter Pan",
    "Alice no País das Maravilhas",
    "Hércules",
    "Pocahontas",
    "As Branquelas",
    "Superbad",
    "Projeto X",
    "Se Beber Não Case",
    "Gente Grande",
    "Todo Mundo em Pânico",
    "Invocação do Mal",
    "Anabelle",
    "Sobrenatural",
    "O Iluminado",
    "Midsommar",
    "Hereditário",
    "Pânico",
    "Sexta-Feira 13",
    "A Hora do Pesadelo",
    "Halloween",
    "Dark",
    "Stranger Things",
    "Sintonia",
    "Jujutsu Kaisen",
    "Demon Slayer",
    "Attack on Titan",
    "Meu Amigo Cachorro",
  ],
  Comidas: [
    "Pizza",
    "Hambúrguer",
    "Feijoada",
    "Brigadeiro",
    "Pão de queijo",
    "Coxinha",
    "Lasanha",
    "Sushi",
    "Pastel",
    "Açaí",
    "Tapioca",
    "Churrasco",
    "Pipoca",
    "Sorvete",
    "Cachorro-quente",
    "Bolo de cenoura",
    "Mandioca",
    "Espaguete",
    "Sopa",
    "Salada",
    "Panqueca",
    "Pudim",
    "Farofa",
    "Moqueca",
    "Lanche da noite",
    "Beirute",
    "Dogão prensado",
    "Podrão",
    "Batata frita com bacon",
    "Nuggets",
    "Pastel de feira",
    "Caldo de cana",
    "Bolinha de queijo",
    "Kibe",
    "Esfiha aberta",
    "Shawarma",
    "Kebab",
    "Poke",
    "Temaki",
    "Hot roll",
    "Yakissoba",
    "Ramen",
    "Frango xadrez",
    "Guioza",
    "Petit gateau",
    "Brownie",
    "Donut",
    "Churros",
    "Fondue",
    "Milkshake",
    "Waffle",
    "Croissant",
    "Pão na chapa",
    "Misto quente",
    "Omelete",
    "Tapioca recheada",
    "Cuscuz paulista",
    "Polenta frita",
    "Torresmo",
    "Estrogonofe de frango",
    "Parmegiana",
    "Arroz carreteiro",
    "Feijão tropeiro",
    "Virado a paulista",
    "Bife a cavalo",
    "Nhoque",
    "Ravioli",
    "Canelone",
    "Mousse de maracujá",
    "Pave",
    "Quindim",
    "Beijinho",
    "Cajuzinho",
    "Doce de leite",
  ],
  Profissões: [
    "Médico",
    "Professor",
    "Bombeiro",
    "Policial",
    "Cozinheiro",
    "Dentista",
    "Piloto",
    "Cantor",
    "Jogador de futebol",
    "Astronauta",
    "Pintor",
    "Carteiro",
    "Veterinário",
    "Engenheiro",
    "Advogado",
    "Jornalista",
    "Pedreiro",
    "Cabeleireiro",
    "Garçom",
    "Fotógrafo",
    "Padeiro",
    "Eletricista",
    "Motorista",
    "Palhaço",
    "Digital Influencer",
    "Youtuber",
    "Streamer",
    "TikToker",
    "MC",
    "DJ",
    "Barbeiro",
    "Programador",
    "Editor de vídeo",
    "Vendedor",
    "Segurança",
    "Bartender",
    "Barista",
    "Chef de cozinha",
    "Personal trainer",
    "Nutricionista",
    "Fisioterapeuta",
    "Psicólogo",
    "Arquiteto",
    "Estilista",
    "Modelo",
    "Ator",
    "Aeromoça",
  ],
  Lugares: [
    "Praia",
    "Hospital",
    "Escola",
    "Supermercado",
    "Cinema",
    "Praça",
    "Aeroporto",
    "Estádio",
    "Floresta",
    "Deserto",
    "Montanha",
    "Igreja",
    "Restaurante",
    "Shopping",
    "Zoológico",
    "Museu",
    "Padaria",
    "Farmácia",
    "Cachoeira",
    "Caverna",
    "Castelo",
    "Fazenda",
    "Biblioteca",
    "Parque",
    "Baile funk",
    "Show de trap",
    "Barbearia",
    "Shopping",
    "Estádio",
    "Parque",
    "Metrô",
    "Aeroporto",
    "Lan house",
    "Boliche",
    "Restaurante",
    "Faculdade",
    "Escritório",
    "Teatro",
    "Galeria de arte",
  ],
};

const CATEGORIAS = Object.keys(WORDS);
const TODAS = "todas";

// Junta o pool de palavras de uma categoria — ou de todas, se for "todas".
function poolDe(categoria) {
  if (categoria === TODAS) {
    return CATEGORIAS.flatMap((c) => WORDS[c]);
  }
  return WORDS[categoria] || [];
}

// Sorteia uma palavra do escopo, evitando repetir as últimas usadas.
// `usadas` é um array de palavras recentes (passado/retornado pelo app.js).
function sortearPalavra(categoria, usadas = []) {
  const pool = poolDe(categoria);
  if (pool.length === 0) return null;

  // Candidatas = pool menos as recentes; se zerar, libera tudo de novo.
  let candidatas = pool.filter((p) => !usadas.includes(p));
  if (candidatas.length === 0) candidatas = pool;

  const i = Math.floor(Math.random() * candidatas.length);
  return candidatas[i];
}
